#:schema node_modules/wrangler/config-schema.json
name = "pt-auto-login"
main = "src/index.ts"
compatibility_date = "2024-10-11"
compatibility_flags = ["nodejs_compat"]

[observability]
enabled = true

[[kv_namespaces]]
binding = "PAL"
id = "dc2d2a2880fe409183508e2cda96282e"

[browser]
binding = "PAL_BROWSER"

[triggers]
crons = ["0 16 * * *"]
